// <auto-generated />
using System;
using Fly_Away.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fly_Away.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fly_Away.Models.Account", b =>
                {
                    b.Property<int>("Account_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Account_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Account_ID");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Fly_Away.Models.Airline", b =>
                {
                    b.Property<int>("Airline_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Airline_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Airline_ID");

                    b.ToTable("Airline", (string)null);
                });

            modelBuilder.Entity("Fly_Away.Models.Airport", b =>
                {
                    b.Property<int>("Airport_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Airport_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Airport_ID");

                    b.ToTable("Airport", (string)null);
                });

            modelBuilder.Entity("Fly_Away.Models.Flight", b =>
                {
                    b.Property<int>("Flight_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Flight_ID"));

                    b.Property<int>("Airline_ID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateArrival")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateDeparture")
                        .HasColumnType("date");

                    b.Property<int>("Destination_ID")
                        .HasColumnType("int");

                    b.Property<int>("Source_ID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("TimeArrival")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TimeDeparture")
                        .HasColumnType("time");

                    b.HasKey("Flight_ID");

                    b.HasIndex("Airline_ID");

                    b.HasIndex("Destination_ID");

                    b.HasIndex("Source_ID");

                    b.ToTable("Flight", (string)null);
                });

            modelBuilder.Entity("Fly_Away.Models.FlightClass", b =>
                {
                    b.Property<int>("FlightClass_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightClass_ID"));

                    b.Property<string>("BaggageSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightClass_ID");

                    b.ToTable("FlightClass", (string)null);
                });

            modelBuilder.Entity("Fly_Away.Models.Gate", b =>
                {
                    b.Property<int>("Gate_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gate_ID"));

                    b.Property<int>("Airport_ID")
                        .HasColumnType("int");

                    b.Property<int>("Flight_ID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Gate_ID");

                    b.HasIndex("Airport_ID");

                    b.HasIndex("Flight_ID");

                    b.ToTable("Gate", (string)null);
                });

            modelBuilder.Entity("Fly_Away.Models.Seat", b =>
                {
                    b.Property<int>("Seat_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Seat_ID"));

                    b.Property<int>("Flight_ID")
                        .HasColumnType("int");

                    b.Property<int>("SeatNum")
                        .HasColumnType("int");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Seat_ID");

                    b.HasIndex("Flight_ID");

                    b.ToTable("Seat", (string)null);
                });

            modelBuilder.Entity("Fly_Away.Models.Ticket", b =>
                {
                    b.Property<int>("Ticket_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ticket_ID"));

                    b.Property<int>("Account_ID")
                        .HasColumnType("int");

                    b.Property<long>("Barcode")
                        .HasColumnType("bigint");

                    b.Property<int>("FlightClass_ID")
                        .HasColumnType("int");

                    b.Property<int>("Flight_ID")
                        .HasColumnType("int");

                    b.Property<int>("Gate_ID")
                        .HasColumnType("int");

                    b.Property<int>("Seat_ID")
                        .HasColumnType("int");

                    b.Property<string>("TicketImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ticket_ID");

                    b.HasIndex("Account_ID");

                    b.HasIndex("FlightClass_ID");

                    b.HasIndex("Flight_ID");

                    b.HasIndex("Gate_ID");

                    b.HasIndex("Seat_ID");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("Fly_Away.Models.Flight", b =>
                {
                    b.HasOne("Fly_Away.Models.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("Airline_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fly_Away.Models.Airport", "Destination")
                        .WithMany()
                        .HasForeignKey("Destination_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fly_Away.Models.Airport", "Source")
                        .WithMany()
                        .HasForeignKey("Source_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Destination");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Fly_Away.Models.Gate", b =>
                {
                    b.HasOne("Fly_Away.Models.Airport", "Airport")
                        .WithMany()
                        .HasForeignKey("Airport_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fly_Away.Models.Flight", "Flight")
                        .WithMany("Gates")
                        .HasForeignKey("Flight_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airport");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Fly_Away.Models.Seat", b =>
                {
                    b.HasOne("Fly_Away.Models.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("Flight_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Fly_Away.Models.Ticket", b =>
                {
                    b.HasOne("Fly_Away.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Account_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fly_Away.Models.FlightClass", "FlightClass")
                        .WithMany()
                        .HasForeignKey("FlightClass_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fly_Away.Models.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("Flight_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fly_Away.Models.Gate", "Gate")
                        .WithMany()
                        .HasForeignKey("Gate_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fly_Away.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("Seat_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Flight");

                    b.Navigation("FlightClass");

                    b.Navigation("Gate");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Fly_Away.Models.Flight", b =>
                {
                    b.Navigation("Gates");

                    b.Navigation("Seats");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
